AWSTemplateFormatVersion: "2010-09-09"
Description: MediaConvert JobTemplate stub

Parameters:
  ProjectName:
    Type: String
  MediaConvertRole:
    Type: String

Resources:
  MediaConvertJobTemplate:
    Type: AWS::MediaConvert::JobTemplate
    Properties:
      Name: !Sub "${ProjectName}-template"
      Description: "Stub template via CFN"
      StatusUpdateInterval: SECONDS_60
      Category: "video-transcoder"
